# Generated by Django 2.2.9 on 2020-01-31 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200130_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='todo_text',
        ),
    ]
