# Generated by Django 2.2.9 on 2020-01-31 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200131_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='todo_text',
        ),
    ]
