# Generated by Django 2.2.9 on 2020-01-31 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200131_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='added_date',
            new_name='created',
        ),
    ]
