# Generated by Django 2.2.9 on 2020-01-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200131_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_text',
            new_name='text',
        ),
    ]
